# Generated by Django 2.2 on 2019-05-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=255)),
                ('class_id', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'grades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('operation', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetrieveQuestions',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('question_1', models.CharField(blank=True, max_length=255, null=True)),
                ('question_2', models.CharField(blank=True, max_length=255, null=True)),
                ('question_3', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_1', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_2', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_3', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'retrieve_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('birthdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
